# -*- coding: utf-8 -*-
"""flaskApp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ydTvtCD8AOQeyNpc1HMVcz1OIK4my0q_
"""

!pip install flask-ngrok

from math import expm1
import joblib
import pandas as pd
from flask import Flask, jsonify, request
from tensorflow import keras
from keras.models import load_model
from keras.preprocessing import image
import numpy as np
from flask_ngrok import run_with_ngrok
model = keras.models.load_model("/content/drive/My Drive/skin_cancer_dataset/model/InceptionResNetV2_rbk_v3.h5")
app = Flask(__name__)
run_with_ngrok(app)   #starts ngrok when the app is run
@app.route("/")
def index():
    data = request.json
    img = image.load_img('/content/drive/My Drive/skin_cancer_dataset/input/skin-cancer-mnist-ham10000/HAM10000_images_part_1/ISIC_0024308.jpg', target_size=(75, 100))
    x = image.img_to_array(img)
    x = np.expand_dims(x, axis=0)

    images = np.vstack([x])
    classes = model.predict_classes(images, batch_size=10)
    return jsonify({"result": str(classes)})
  
app.run()